### ISSUE TITLE
依存関係のセキュリティ監査

### ISSUE THREAD

**Issue by keito4** [keito4/notion_orm#45]
## 概要
`npm audit`やDependabot設定がなく、定期的なセキュリティチェックとアップデートの自動化が必要。

## 問題
- 依存関係の脆弱性チェックが自動化されていない
- セキュリティアップデートの通知がない
- 定期的な依存関係更新プロセスがない
- 古いパッケージバージョンのリスクが管理されていない

## 現在の依存関係
```json
// package.json - セキュリティ監査が不足
"dependencies": {
  "@notionhq/client": "^2.2.15",
  "chalk": "^5.4.1",
  "commander": "^12.1.0",
  "ts-node": "^10.9.2"
}
```

## 必要な機能
1. **自動セキュリティ監査**
   - GitHub Dependabot設定
   - CI/CDでの`npm audit`実行
   - 脆弱性レポートの自動生成

2. **定期的な更新**
   - 依存関係の自動更新PR
   - セキュリティパッチの優先適用
   - 破綻的変更の検出

3. **監視とレポート**
   - セキュリティダッシュボード
   - 脆弱性の重要度分類
   - 修正期限の設定

## 作業内容
- [ ] `.github/dependabot.yml`の作成
- [ ] GitHub Security Advisoriesの有効化
- [ ] CI/CDワークフローに`npm audit`追加
- [ ] 脆弱性修正のワークフロー定義
- [ ] 依存関係更新のポリシー策定
- [ ] セキュリティテストの追加
- [ ] package-lock.jsonの定期的な更新
- [ ] セキュリティ関連ドキュメントの作成

## Dependabot設定例
```yaml
# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
```

## CI/CDでの監査
```yaml
# GitHub Actions - セキュリティチェック
- name: Security Audit
  run: |
    npm audit --audit-level high
    npm audit --json > audit-report.json
```

## 期待する効果
- 脆弱性の早期発見と修正
- 依存関係の最新状態維持
- セキュリティリスクの可視化
- 自動化による作業負荷軽減

## 参考
- [GitHub Dependabot](https://docs.github.com/en/code-security/dependabot)
- [npm audit](https://docs.npmjs.com/cli/v8/commands/npm-audit)
- [Node.js Security Best Practices](https://nodejs.org/en/docs/guides/security/)
